---
- block:
  - name: install scm packages
    apt: "name={{ packages }}  state=latest"
    vars:
      packages:
        - mercurial
        - git
  - name: get root of base dir
    shell: "dirname {{ php_fpmapp_basedir }}"
    register: root_dir
  - name: create root of base dir
    file: "path={{ root_dir.stdout }} state=directory mode=0755"
  
  - name: check if the project directory exists
    stat: "path={{ php_fpmapp_basedir }}"
    register: p
  - name: delete dest dir if exists
    command: "rm -rf {{ php_fpmapp_basedir }}"
    when: "p.stat.isdir is defined and p.stat.isdir"
  
  - name: add github and bitbucket to ssh known hosts
    script: "add_ssh_known_hosts.sh"
  - name: checkout source code via scm
    command: "{{ php_fpmapp_scm }} clone {{ php_fpmapp_repo }} {{ php_fpmapp_basedir }}"
  
  - name: install nginx configuration of the project
    template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/sites-available/{{ php_fpmapp_domain_name }}.conf"
  
  - name: activate nginx configuration of the project
    file:
      src: "/etc/nginx/sites-available/{{ php_fpmapp_domain_name }}.conf"
      dest: "/etc/nginx/sites-enabled/{{ php_fpmapp_domain_name }}.conf"
      state: "link"
  tags:
    - php_fpmapp
