---
- block:
  - name: install scm packages
    ansible.builtin.apt: "name={{ packages }}  state=latest"
    vars:
      packages:
        - mercurial
        - git
  
  - name: create web root dir                                                                                                                                                                 
    ansible.builtin.file:                                                                                                                                                                                     
      path: "{{ php_fpmapps_web_base_dir }}"                                                                                                                                              
      state: "directory"                                                                                                                                                                      
      mode: "0711"                                                                                                                                                                            
      owner: "root"                                                                                                                                                                           
      group: "root"
  
  - name: checkout source code via scm                                                                                                                                                        
    ansible.builtin.command: "{{ item.scm }} clone {{ item.repo_url }} {{ item.base_dir }}"                                                                                                                   
    args:                                                                                                                                                                                     
      creates: "{{ item.base_dir }}"                                                                                                                                                          
    loop: "{{ php_fpmapps_vars }}"

  - name: install nginx configuration of the project
    ansible.builtin.template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/sites-available/{{ item.domain_name }}.conf"
    loop: "{{ php_fpmapps_vars }}"
  
  - name: activate nginx configuration of the project
    ansible.builtin.file:
      src: "/etc/nginx/sites-available/{{ item.domain_name }}.conf"
      dest: "/etc/nginx/sites-enabled/{{ item.domain_name }}.conf"
      state: "link"
    loop: "{{ php_fpmapps_vars }}"
  tags:
    - php_fpmapps
